"""Local leaderboard tracking for Parameter Golf experiments."""

import csv
import os
from datetime import datetime, timezone

from config import LEADERBOARD_CSV, LEADERBOARD_MD

CSV_FIELDS = [
    "timestamp",
    "run_name",
    "script",
    "gpus",
    "val_bpb",
    "final_int8_val_bpb",
    "final_ttt_val_bpb",
    "submission_bytes",
    "wallclock_s",
    "exit_code",
    "notes",
]


def add_result(result: dict, script_name: str = "", gpus: int = 1, notes: str = ""):
    """Append a result to the CSV and regenerate the markdown leaderboard."""
    wallclock_s = None
    if result.get("wallclock_ms") is not None:
        wallclock_s = round(result["wallclock_ms"] / 1000, 1)
    elif result.get("elapsed_s") is not None:
        wallclock_s = result["elapsed_s"]

    row = {
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
        "run_name": result.get("run_name", ""),
        "script": script_name,
        "gpus": gpus,
        "val_bpb": result.get("val_bpb", ""),
        "final_int8_val_bpb": result.get("final_int8_val_bpb", ""),
        "final_ttt_val_bpb": result.get("final_ttt_val_bpb", ""),
        "submission_bytes": result.get("submission_bytes", ""),
        "wallclock_s": wallclock_s or "",
        "exit_code": result.get("exit_code", ""),
        "notes": notes,
    }

    # Append to CSV
    write_header = not os.path.exists(LEADERBOARD_CSV)
    with open(LEADERBOARD_CSV, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        if write_header:
            writer.writeheader()
        writer.writerow(row)

    # Regenerate markdown
    _render_markdown()


def load_results() -> list[dict]:
    """Load all results from the CSV."""
    if not os.path.exists(LEADERBOARD_CSV):
        return []
    with open(LEADERBOARD_CSV, newline="") as f:
        return list(csv.DictReader(f))


def _render_markdown():
    """Regenerate LEADERBOARD.md from the CSV."""
    results = load_results()

    # Sort by best score (final_int8_val_bpb, then val_bpb)
    def sort_key(r):
        for field in ("final_int8_val_bpb", "val_bpb"):
            v = r.get(field, "")
            if v:
                try:
                    return float(v)
                except ValueError:
                    pass
        return float("inf")

    results.sort(key=sort_key)

    lines = [
        "# Parameter Golf -- Local Leaderboard",
        "",
        "Auto-generated by `infra/leaderboard.py`. Do not edit manually.",
        "",
        "| # | Run | Script | val_bpb | int8_bpb | ttt_bpb | Size (KB) | GPUs | Time | Date | Notes |",
        "|---|-----|--------|---------|----------|---------|-----------|------|------|------|-------|",
    ]

    for i, r in enumerate(results, 1):
        size_kb = ""
        if r.get("submission_bytes"):
            try:
                size_kb = f"{int(r['submission_bytes']) // 1024:,}"
            except (ValueError, TypeError):
                pass

        wallclock = ""
        if r.get("wallclock_s"):
            try:
                secs = float(r["wallclock_s"])
                mins = int(secs // 60)
                remaining = int(secs % 60)
                wallclock = f"{mins}m{remaining:02d}s"
            except (ValueError, TypeError):
                pass

        date = r.get("timestamp", "")[:10]
        exit_code = r.get("exit_code", "0")
        status = "" if str(exit_code) == "0" else f"FAILED({exit_code})"
        notes = r.get("notes", "")
        if status:
            notes = f"{status} {notes}".strip()

        lines.append(
            f"| {i} "
            f"| {r.get('run_name', '')} "
            f"| {r.get('script', '')} "
            f"| {r.get('val_bpb', '')} "
            f"| {r.get('final_int8_val_bpb', '')} "
            f"| {r.get('final_ttt_val_bpb', '')} "
            f"| {size_kb} "
            f"| {r.get('gpus', '')} "
            f"| {wallclock} "
            f"| {date} "
            f"| {notes} |"
        )

    lines.append("")
    with open(LEADERBOARD_MD, "w") as f:
        f.write("\n".join(lines))


def print_summary(result: dict, gpus: int = 1):
    """Print a concise summary of a run result."""
    from config import H100_COST_PER_HOUR

    elapsed = result.get("elapsed_s", 0) or 0
    cost = gpus * (elapsed / 3600) * H100_COST_PER_HOUR

    print("\n" + "=" * 60)
    print(f"  Run:           {result.get('run_name', '?')}")
    print(f"  Exit code:     {result.get('exit_code', '?')}")
    print(f"  val_bpb:       {result.get('val_bpb', 'N/A')}")
    print(f"  int8 val_bpb:  {result.get('final_int8_val_bpb', 'N/A')}")
    print(f"  ttt val_bpb:   {result.get('final_ttt_val_bpb', 'N/A')}")
    print(f"  Submission:    {result.get('submission_bytes', 'N/A')} bytes")
    print(f"  Wallclock:     {elapsed:.0f}s")
    print(f"  Est. cost:     ${cost:.2f}")
    print("=" * 60 + "\n")
